language: python

env:
  - TOX_ENV=flake8
  - TOX_ENV=py37-dj111-cms37
  - TOX_ENV=py37-dj111-cms36
  - TOX_ENV=py37-dj111-cms35
  - TOX_ENV=py36-dj111-cms37
  - TOX_ENV=py36-dj111-cms36
  - TOX_ENV=py36-dj111-cms35
  - TOX_ENV=py35-dj111-cms37
  - TOX_ENV=py35-dj111-cms36
  - TOX_ENV=py35-dj111-cms35

install:
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
